# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2psims/protos/initiator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'p2psims/protos/initiator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from p2psims.protos import peer_pb2 as p2psims_dot_protos_dot_peer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ep2psims/protos/initiator.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19p2psims/protos/peer.proto\"\x9d\x01\n\x0fJoinZoneRequest\x12*\n\x08\x64\x65\x63ision\x18\x01 \x01(\x0e\x32\x18.protos.JoinZoneDecision\x12\x1e\n\x11initiator_address\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x1f\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0c.protos.DataH\x01\x88\x01\x01\x42\x14\n\x12_initiator_addressB\x07\n\x05_data*6\n\x10JoinZoneDecision\x12\n\n\x06\x41\x43\x43\x45PT\x10\x00\x12\n\n\x06REJECT\x10\x01\x12\n\n\x06INFORM\x10\x02\x32L\n\rZoneInitiator\x12;\n\x08JoinZone\x12\x17.protos.JoinZoneRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2psims.protos.initiator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINZONEDECISION']._serialized_start=258
  _globals['_JOINZONEDECISION']._serialized_end=312
  _globals['_JOINZONEREQUEST']._serialized_start=99
  _globals['_JOINZONEREQUEST']._serialized_end=256
  _globals['_ZONEINITIATOR']._serialized_start=314
  _globals['_ZONEINITIATOR']._serialized_end=390
# @@protoc_insertion_point(module_scope)
