# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2psims/protos/peer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'p2psims/protos/peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19p2psims/protos/peer.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\"3\n\x16SuggestJoinZoneRequest\x12\x19\n\x11initiator_address\x18\x02 \x01(\t\"i\n#SuggestClusterRepresentativeRequest\x12\r\n\x05\x66orce\x18\x01 \x01(\x08\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x12\x17\n\x0fpeers_addresses\x18\x03 \x03(\tB\x07\n\x05_data\"6\n$SuggestClusterRepresentativeResponse\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\x08\"\x85\x01\n\x04\x44\x61ta\x12\x42\n\x14peers_addresses_data\x18\x01 \x03(\x0b\x32$.protos.Data.PeersAddressesDataEntry\x1a\x39\n\x17PeersAddressesDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"A\n\x1bMigrateZoneInitiatorRequest\x12\"\n\x1anew_zone_initiator_address\x18\x01 \x01(\t\"\xc5\x01\n\x1dPromoteToZoneInitiatorRequest\x12[\n\x14peers_addresses_data\x18\x01 \x03(\x0b\x32=.protos.PromoteToZoneInitiatorRequest.PeersAddressesDataEntry\x1aG\n\x17PeersAddressesDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1b\n\x05value\x18\x02 \x01(\x0b\x32\x0c.protos.Data:\x02\x38\x01\x32\xfa\x02\n\x04Peer\x12I\n\x0fSuggestJoinZone\x12\x1e.protos.SuggestJoinZoneRequest\x1a\x16.google.protobuf.Empty\x12y\n\x1cSuggestClusterRepresentative\x12+.protos.SuggestClusterRepresentativeRequest\x1a,.protos.SuggestClusterRepresentativeResponse\x12S\n\x14MigrateZoneInitiator\x12#.protos.MigrateZoneInitiatorRequest\x1a\x16.google.protobuf.Empty\x12W\n\x16PromoteToZoneInitiator\x12%.protos.PromoteToZoneInitiatorRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2psims.protos.peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA_PEERSADDRESSESDATAENTRY']._loaded_options = None
  _globals['_DATA_PEERSADDRESSESDATAENTRY']._serialized_options = b'8\001'
  _globals['_PROMOTETOZONEINITIATORREQUEST_PEERSADDRESSESDATAENTRY']._loaded_options = None
  _globals['_PROMOTETOZONEINITIATORREQUEST_PEERSADDRESSESDATAENTRY']._serialized_options = b'8\001'
  _globals['_SUGGESTJOINZONEREQUEST']._serialized_start=66
  _globals['_SUGGESTJOINZONEREQUEST']._serialized_end=117
  _globals['_SUGGESTCLUSTERREPRESENTATIVEREQUEST']._serialized_start=119
  _globals['_SUGGESTCLUSTERREPRESENTATIVEREQUEST']._serialized_end=224
  _globals['_SUGGESTCLUSTERREPRESENTATIVERESPONSE']._serialized_start=226
  _globals['_SUGGESTCLUSTERREPRESENTATIVERESPONSE']._serialized_end=280
  _globals['_DATA']._serialized_start=283
  _globals['_DATA']._serialized_end=416
  _globals['_DATA_PEERSADDRESSESDATAENTRY']._serialized_start=359
  _globals['_DATA_PEERSADDRESSESDATAENTRY']._serialized_end=416
  _globals['_MIGRATEZONEINITIATORREQUEST']._serialized_start=418
  _globals['_MIGRATEZONEINITIATORREQUEST']._serialized_end=483
  _globals['_PROMOTETOZONEINITIATORREQUEST']._serialized_start=486
  _globals['_PROMOTETOZONEINITIATORREQUEST']._serialized_end=683
  _globals['_PROMOTETOZONEINITIATORREQUEST_PEERSADDRESSESDATAENTRY']._serialized_start=612
  _globals['_PROMOTETOZONEINITIATORREQUEST_PEERSADDRESSESDATAENTRY']._serialized_end=683
  _globals['_PEER']._serialized_start=686
  _globals['_PEER']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
