# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from p2psims.protos import peer_pb2 as p2psims_dot_protos_dot_peer__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in p2psims/protos/peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SuggestJoinZone = channel.unary_unary(
                '/protos.Peer/SuggestJoinZone',
                request_serializer=p2psims_dot_protos_dot_peer__pb2.SuggestJoinZoneRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SuggestClusterRepresentative = channel.unary_unary(
                '/protos.Peer/SuggestClusterRepresentative',
                request_serializer=p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeRequest.SerializeToString,
                response_deserializer=p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeResponse.FromString,
                _registered_method=True)
        self.MigrateZoneInitiator = channel.unary_unary(
                '/protos.Peer/MigrateZoneInitiator',
                request_serializer=p2psims_dot_protos_dot_peer__pb2.MigrateZoneInitiatorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PromoteToZoneInitiator = channel.unary_unary(
                '/protos.Peer/PromoteToZoneInitiator',
                request_serializer=p2psims_dot_protos_dot_peer__pb2.PromoteToZoneInitiatorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PeerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SuggestJoinZone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestClusterRepresentative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateZoneInitiator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteToZoneInitiator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SuggestJoinZone': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestJoinZone,
                    request_deserializer=p2psims_dot_protos_dot_peer__pb2.SuggestJoinZoneRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SuggestClusterRepresentative': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestClusterRepresentative,
                    request_deserializer=p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeRequest.FromString,
                    response_serializer=p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeResponse.SerializeToString,
            ),
            'MigrateZoneInitiator': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateZoneInitiator,
                    request_deserializer=p2psims_dot_protos_dot_peer__pb2.MigrateZoneInitiatorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PromoteToZoneInitiator': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteToZoneInitiator,
                    request_deserializer=p2psims_dot_protos_dot_peer__pb2.PromoteToZoneInitiatorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Peer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.Peer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Peer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SuggestJoinZone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Peer/SuggestJoinZone',
            p2psims_dot_protos_dot_peer__pb2.SuggestJoinZoneRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SuggestClusterRepresentative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Peer/SuggestClusterRepresentative',
            p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeRequest.SerializeToString,
            p2psims_dot_protos_dot_peer__pb2.SuggestClusterRepresentativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateZoneInitiator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Peer/MigrateZoneInitiator',
            p2psims_dot_protos_dot_peer__pb2.MigrateZoneInitiatorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteToZoneInitiator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.Peer/PromoteToZoneInitiator',
            p2psims_dot_protos_dot_peer__pb2.PromoteToZoneInitiatorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
