# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2psims/protos/representative.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'p2psims/protos/representative.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#p2psims/protos/representative.proto\x12\x06protos\x1a\x1bgoogle/protobuf/empty.proto\"u\n\rSearchRequest\x12\r\n\x05\x64\x61tum\x18\x01 \x01(\x0c\x12\t\n\x01k\x18\x02 \x01(\r\x12\x16\n\x0emin_similarity\x18\x03 \x01(\x01\x12\x1d\n\x10sequential_top_k\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x13\n\x11_sequential_top_k\"s\n\x0eSearchResponse\x12\x32\n\x06scores\x18\x01 \x03(\x0b\x32\".protos.SearchResponse.ScoresEntry\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\".\n\x0cNodeIdentity\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\r\"^\n*PromoteToSuperClusterRepresentativeRequest\x12\x30\n(super_clusters_representatives_addresses\x18\x01 \x03(\t\"\'\n\x16ImmediateSearchRequest\x12\r\n\x05\x64\x61tum\x18\x01 \x01(\x0c\"(\n\x17ImmediateSearchResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x32\xed\x02\n\x15\x43lusterRepresentative\x12\x37\n\x06Search\x12\x15.protos.SearchRequest\x1a\x16.protos.SearchResponse\x12q\n#PromoteToSuperClusterRepresentative\x12\x32.protos.PromoteToSuperClusterRepresentativeRequest\x1a\x16.google.protobuf.Empty\x12T\n$AdvertiseSearchClusterRepresentative\x12\x14.protos.NodeIdentity\x1a\x16.google.protobuf.Empty\x12R\n\x0fImmediateSearch\x12\x1e.protos.ImmediateSearchRequest\x1a\x1f.protos.ImmediateSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2psims.protos.representative_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHRESPONSE_SCORESENTRY']._loaded_options = None
  _globals['_SEARCHRESPONSE_SCORESENTRY']._serialized_options = b'8\001'
  _globals['_SEARCHREQUEST']._serialized_start=76
  _globals['_SEARCHREQUEST']._serialized_end=193
  _globals['_SEARCHRESPONSE']._serialized_start=195
  _globals['_SEARCHRESPONSE']._serialized_end=310
  _globals['_SEARCHRESPONSE_SCORESENTRY']._serialized_start=265
  _globals['_SEARCHRESPONSE_SCORESENTRY']._serialized_end=310
  _globals['_NODEIDENTITY']._serialized_start=312
  _globals['_NODEIDENTITY']._serialized_end=358
  _globals['_PROMOTETOSUPERCLUSTERREPRESENTATIVEREQUEST']._serialized_start=360
  _globals['_PROMOTETOSUPERCLUSTERREPRESENTATIVEREQUEST']._serialized_end=454
  _globals['_IMMEDIATESEARCHREQUEST']._serialized_start=456
  _globals['_IMMEDIATESEARCHREQUEST']._serialized_end=495
  _globals['_IMMEDIATESEARCHRESPONSE']._serialized_start=497
  _globals['_IMMEDIATESEARCHRESPONSE']._serialized_end=537
  _globals['_CLUSTERREPRESENTATIVE']._serialized_start=540
  _globals['_CLUSTERREPRESENTATIVE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
