# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from p2psims.protos import representative_pb2 as p2psims_dot_protos_dot_representative__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in p2psims/protos/representative_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterRepresentativeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/protos.ClusterRepresentative/Search',
                request_serializer=p2psims_dot_protos_dot_representative__pb2.SearchRequest.SerializeToString,
                response_deserializer=p2psims_dot_protos_dot_representative__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.PromoteToSuperClusterRepresentative = channel.unary_unary(
                '/protos.ClusterRepresentative/PromoteToSuperClusterRepresentative',
                request_serializer=p2psims_dot_protos_dot_representative__pb2.PromoteToSuperClusterRepresentativeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AdvertiseSearchClusterRepresentative = channel.unary_unary(
                '/protos.ClusterRepresentative/AdvertiseSearchClusterRepresentative',
                request_serializer=p2psims_dot_protos_dot_representative__pb2.NodeIdentity.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ImmediateSearch = channel.unary_unary(
                '/protos.ClusterRepresentative/ImmediateSearch',
                request_serializer=p2psims_dot_protos_dot_representative__pb2.ImmediateSearchRequest.SerializeToString,
                response_deserializer=p2psims_dot_protos_dot_representative__pb2.ImmediateSearchResponse.FromString,
                _registered_method=True)


class ClusterRepresentativeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteToSuperClusterRepresentative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvertiseSearchClusterRepresentative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImmediateSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterRepresentativeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=p2psims_dot_protos_dot_representative__pb2.SearchRequest.FromString,
                    response_serializer=p2psims_dot_protos_dot_representative__pb2.SearchResponse.SerializeToString,
            ),
            'PromoteToSuperClusterRepresentative': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteToSuperClusterRepresentative,
                    request_deserializer=p2psims_dot_protos_dot_representative__pb2.PromoteToSuperClusterRepresentativeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AdvertiseSearchClusterRepresentative': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvertiseSearchClusterRepresentative,
                    request_deserializer=p2psims_dot_protos_dot_representative__pb2.NodeIdentity.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ImmediateSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ImmediateSearch,
                    request_deserializer=p2psims_dot_protos_dot_representative__pb2.ImmediateSearchRequest.FromString,
                    response_serializer=p2psims_dot_protos_dot_representative__pb2.ImmediateSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.ClusterRepresentative', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.ClusterRepresentative', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterRepresentative(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.ClusterRepresentative/Search',
            p2psims_dot_protos_dot_representative__pb2.SearchRequest.SerializeToString,
            p2psims_dot_protos_dot_representative__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteToSuperClusterRepresentative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.ClusterRepresentative/PromoteToSuperClusterRepresentative',
            p2psims_dot_protos_dot_representative__pb2.PromoteToSuperClusterRepresentativeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvertiseSearchClusterRepresentative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.ClusterRepresentative/AdvertiseSearchClusterRepresentative',
            p2psims_dot_protos_dot_representative__pb2.NodeIdentity.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImmediateSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.ClusterRepresentative/ImmediateSearch',
            p2psims_dot_protos_dot_representative__pb2.ImmediateSearchRequest.SerializeToString,
            p2psims_dot_protos_dot_representative__pb2.ImmediateSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
